name: RedBlackTree Setup and Testrun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [clang-latest, gcc-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1477b21f02be01bcb8030d50f37cfec92bfa615b6
      with: 
        ruby-version:  2.5.8
    - name : Checkout redblacktree
      shell: bash
      run  : git submodule update --init --recursive
    - name : Install ceedling
      run  : gem install ceedling
    - name : Testrun RBT
      run  : ceedling test:all